// Generated by tools/sync-plugins.js; do not edit by hand.
module.exports = {
  "2024": {
    "$schema": "https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/schema.json",
    "$id": "https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/2024.json",
    "year": 2024,
    "papers": [
      "https://www.gov.cn/zhengce/zhengceku/202310/content_6911528.htm"
    ],
    "days": [
      {
        "name": "元旦",
        "date": "2024-01-01",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-04",
        "isOffDay": false
      },
      {
        "name": "春节",
        "date": "2024-02-10",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-11",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-12",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-13",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-14",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-15",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-16",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-17",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2024-02-18",
        "isOffDay": false
      },
      {
        "name": "清明节",
        "date": "2024-04-04",
        "isOffDay": true
      },
      {
        "name": "清明节",
        "date": "2024-04-05",
        "isOffDay": true
      },
      {
        "name": "清明节",
        "date": "2024-04-06",
        "isOffDay": true
      },
      {
        "name": "清明节",
        "date": "2024-04-07",
        "isOffDay": false
      },
      {
        "name": "劳动节",
        "date": "2024-04-28",
        "isOffDay": false
      },
      {
        "name": "劳动节",
        "date": "2024-05-01",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2024-05-02",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2024-05-03",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2024-05-04",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2024-05-05",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2024-05-11",
        "isOffDay": false
      },
      {
        "name": "端午节",
        "date": "2024-06-10",
        "isOffDay": true
      },
      {
        "name": "中秋节",
        "date": "2024-09-14",
        "isOffDay": false
      },
      {
        "name": "中秋节",
        "date": "2024-09-15",
        "isOffDay": true
      },
      {
        "name": "中秋节",
        "date": "2024-09-16",
        "isOffDay": true
      },
      {
        "name": "中秋节",
        "date": "2024-09-17",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-09-29",
        "isOffDay": false
      },
      {
        "name": "国庆节",
        "date": "2024-10-01",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-10-02",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-10-03",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-10-04",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-10-05",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-10-06",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-10-07",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2024-10-12",
        "isOffDay": false
      }
    ]
  },
  "2025": {
    "$schema": "https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/schema.json",
    "$id": "https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/2025.json",
    "year": 2025,
    "papers": [
      "https://www.gov.cn/zhengce/zhengceku/202411/content_6986383.htm"
    ],
    "days": [
      {
        "name": "元旦",
        "date": "2025-01-01",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-01-26",
        "isOffDay": false
      },
      {
        "name": "春节",
        "date": "2025-01-28",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-01-29",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-01-30",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-01-31",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-02-01",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-02-02",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-02-03",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-02-04",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2025-02-08",
        "isOffDay": false
      },
      {
        "name": "清明节",
        "date": "2025-04-04",
        "isOffDay": true
      },
      {
        "name": "清明节",
        "date": "2025-04-05",
        "isOffDay": true
      },
      {
        "name": "清明节",
        "date": "2025-04-06",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2025-04-27",
        "isOffDay": false
      },
      {
        "name": "劳动节",
        "date": "2025-05-01",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2025-05-02",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2025-05-03",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2025-05-04",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2025-05-05",
        "isOffDay": true
      },
      {
        "name": "端午节",
        "date": "2025-05-31",
        "isOffDay": true
      },
      {
        "name": "端午节",
        "date": "2025-06-01",
        "isOffDay": true
      },
      {
        "name": "端午节",
        "date": "2025-06-02",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-09-28",
        "isOffDay": false
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-01",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-02",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-03",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-04",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-05",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-06",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-07",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-08",
        "isOffDay": true
      },
      {
        "name": "国庆节、中秋节",
        "date": "2025-10-11",
        "isOffDay": false
      }
    ]
  },
  "2026": {
    "year": 2026,
    "papers": [
      "https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm"
    ],
    "days": [
      {
        "name": "元旦",
        "date": "2026-01-01",
        "isOffDay": true
      },
      {
        "name": "元旦",
        "date": "2026-01-02",
        "isOffDay": true
      },
      {
        "name": "元旦",
        "date": "2026-01-03",
        "isOffDay": true
      },
      {
        "name": "元旦",
        "date": "2026-01-04",
        "isOffDay": false
      },
      {
        "name": "春节",
        "date": "2026-02-14",
        "isOffDay": false
      },
      {
        "name": "春节",
        "date": "2026-02-15",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-16",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-17",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-18",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-19",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-20",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-21",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-22",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-23",
        "isOffDay": true
      },
      {
        "name": "春节",
        "date": "2026-02-28",
        "isOffDay": false
      },
      {
        "name": "清明节",
        "date": "2026-04-04",
        "isOffDay": true
      },
      {
        "name": "清明节",
        "date": "2026-04-05",
        "isOffDay": true
      },
      {
        "name": "清明节",
        "date": "2026-04-06",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2026-05-01",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2026-05-02",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2026-05-03",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2026-05-04",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2026-05-05",
        "isOffDay": true
      },
      {
        "name": "劳动节",
        "date": "2026-05-09",
        "isOffDay": false
      },
      {
        "name": "端午节",
        "date": "2026-06-19",
        "isOffDay": true
      },
      {
        "name": "端午节",
        "date": "2026-06-20",
        "isOffDay": true
      },
      {
        "name": "端午节",
        "date": "2026-06-21",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-09-20",
        "isOffDay": false
      },
      {
        "name": "中秋节",
        "date": "2026-09-25",
        "isOffDay": true
      },
      {
        "name": "中秋节",
        "date": "2026-09-26",
        "isOffDay": true
      },
      {
        "name": "中秋节",
        "date": "2026-09-27",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-01",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-02",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-03",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-04",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-05",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-06",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-07",
        "isOffDay": true
      },
      {
        "name": "国庆节",
        "date": "2026-10-10",
        "isOffDay": false
      }
    ]
  }
};
