import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import * as M from '../src/careModel.js';
const require = createRequire(import.meta.url);
const Mini = require('../../miniprogram/core/careModel.js');
for (const [platform, model] of [['web',M],['wechat',Mini]]) {
 const now = new Date(2026,8,9,9,0), state={plugins:{'elder-care':{storage:{reminders:[{id:'legacy',title:'旧提醒',time:'10:00',repeat:'daily',enabled:true}]}}}};
 const c=model.careState(state);model.careState(state); assert.equal(c.reminders.length,1,'旧插件只迁移一次');
 const once=model.addReminder(c,{title:'喝水',time:'09:00',repeat:'once'},now);
 assert.equal(model.dueItems(c,now).length,1);
 const item=model.dueItems(c,now)[0];model.recordAction(c,item.key,'delivered',now.getTime());
 assert.equal(model.dueItems(c,now).length,0,'已提醒不重复弹窗');
 model.recordAction(c,item.key,'snooze',now.getTime());
 assert.equal(model.dueItems(c,new Date(2026,8,9,9,9)).length,0);
 assert.equal(model.dueItems(c,new Date(2026,8,9,9,10)).length,1);
 model.recordAction(c,item.key,'done',now.getTime());assert.equal(model.dueItems(c,new Date(2026,8,9,9,11)).length,0);
 assert.equal(model.todayItems(c,new Date(2026,8,10,9,0)).some(r=>r.id===once.id),false,'仅一次不在第二天复现');
 const work=model.addReminder(c,{title:'工作日提醒',time:'08:00',repeat:'weekdays'},now);
 assert.equal(model.occurs(work,new Date(2026,8,12)),false);
 assert.equal(model.occurs(work,new Date(2026,8,14)),true);
 const late=model.addReminder(c,{title:'睡前',time:'23:58',repeat:'once'},now);
 const key=late.id+'@2026-09-09';model.recordAction(c,key,'snooze',new Date(2026,8,9,23,58).getTime());
 assert.equal(model.todayItems(c,new Date(2026,8,10,0,8)).find(r=>r.id===late.id).key,key,'跨午夜稍后提醒保留原实例');
 assert.throws(()=>model.addReminder(c,{title:'',time:'09:00'},now));
 assert.throws(()=>model.addReminder(c,{title:'坏时间',time:'25:00'},now));
 console.log('PASS '+platform+': 迁移、一次/每日/工作日、去重、稍后、完成、跨午夜和输入验证');
}
globalThis.wx = { getStorageSync:()=>null, setStorageSync:()=>{}, showToast:()=>{} };
const Care = require('../../miniprogram/core/care.js');
assert.equal(Buffer.from(Care.utf8('按医嘱用药💊')).toString('utf8'),'按医嘱用药💊');
console.log('PASS BLE 中文与 emoji UTF-8 编码');
