// Generated by tools/sync-plugins.js; edit desktop plugin manifests then rerun the sync script.
const plugins = [
  {
    "id": "shiguang-schedule",
    "name": "课程表",
    "version": "2.2.0",
    "author": "基于 XingHeYuZhuan/shiguangschedule · Le时间管理适配",
    "icon": "calendar-days",
    "faIcon": "calendar-days",
    "description": "自适应课程表：桌面 7 列、平板自动分栏、手机纵向日程；支持手动课程、JSON/ICS 备份，以及从教务系统复制表格或导入 CSV/TSV/TXT/HTML 后预览并合并/替换。",
    "permissions": [
      "ui",
      "storage",
      "blocks",
      "notify"
    ],
    "entry": "main.js",
    "order": 1,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "web-collector",
    "name": "网页收集",
    "version": "1.0.0",
    "author": "Le时间管理内置",
    "icon": "bookmark",
    "faIcon": "bookmark",
    "description": "输入网址自动读取网站名称、favicon，并智能匹配 Font Awesome 图标；支持搜索、备注、刷新元信息和一键打开。",
    "permissions": [
      "ui",
      "storage",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 2,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "school-notice",
    "name": "学校通知网站",
    "version": "1.1.0",
    "author": "Le时间管理内置",
    "icon": "school",
    "faIcon": "school",
    "description": "输入学校公告/通知网址后自动识别常见高校 CMS 列表；支持会话登录、用户名密码和手动验证码，并可把公告转成 Le时间管理提醒。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 3,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "pomodoro",
    "name": "番茄专注",
    "version": "0.1.0",
    "author": "Le时间管理内置",
    "icon": "hourglass-half",
    "faIcon": "hourglass-half",
    "description": "环形番茄钟：挑一个任务开始专注，25 分钟后休息。完成的番茄会计入统计，也可通过事件被其他插件感知。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "events"
    ],
    "entry": "main.js",
    "order": 4,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "weekly-report",
    "name": "周度报告",
    "version": "0.1.0",
    "author": "Le时间管理内置",
    "icon": "chart-column",
    "faIcon": "chart-column",
    "description": "按周汇总：每天的时间块分布、分类占比、任务完成度，一眼看清这一周过得怎么样。",
    "permissions": [
      "ui",
      "tasks",
      "blocks"
    ],
    "entry": "main.js",
    "order": 5,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "gx-news",
    "name": "竞赛消息雷达",
    "version": "0.1.0",
    "author": "Le时间管理内置",
    "icon": "trophy",
    "faIcon": "trophy",
    "description": "抓取摩课云竞赛平台（gxxsjs.com）的竞赛通知与资讯：关键词过滤、类型筛选、已读标记、自动刷新，并可一键把带时间的消息转成Le时间管理提醒。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 7,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "chaoxing-notify",
    "name": "学习通",
    "version": "2.1.0",
    "author": "基于 dsh-user/chaoxing-notify-skill v2.0.0 · Le时间管理适配",
    "icon": "graduation-cap",
    "faIcon": "graduation-cap",
    "description": "学习通通知与待办：使用 notice.chaoxing.com 收件箱主路径（无需旧消息接口 IP 白名单），支持账号密码或 Cookie 登录、完整通知正文、课程列表、分享码查询、作业/考试截止时间识别，并可一键转为 Le时间管理提醒。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 8,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "cppu-notify",
    "name": "警大门户通知",
    "version": "1.2.1",
    "author": "基于 dsh-user/cppu-notify-skill v1.2.1",
    "icon": "building-columns",
    "faIcon": "building-columns",
    "description": "智慧警大门户通知：SSO 验证码登录、当前会话续期、按月筛选、正文阅读与转为提醒。密码不保存，退出应用后可能需要重新登录。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 9,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "wechat-push",
    "name": "微信提醒推送",
    "version": "1.1.0",
    "author": "Le时间管理内置",
    "icon": "comment-dots",
    "faIcon": "comment-dots",
    "description": "通过 PushPlus（推荐）把时间块与任务截止提醒推送到微信，支持 Token、可选 Topic 群组和测试消息；兼容旧版 Server酱配置。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "http"
    ],
    "entry": "main.js",
    "order": 10,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "cn-holiday",
    "name": "中国节假日",
    "version": "0.2.0",
    "author": "Le时间管理内置 · 数据源 NateScarlet/holiday-cn",
    "icon": "calendar-day",
    "faIcon": "calendar-day",
    "description": "中国法定节假日、调休上班日和下次休息日；内置 2024–2026 离线数据，首屏不再探测未公布年份，缺失年份按需联网并缓存。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http"
    ],
    "entry": "main.js",
    "order": 11,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "exam-calendar",
    "name": "考试日历",
    "version": "0.2.0",
    "author": "your-name",
    "icon": "calendar-check",
    "faIcon": "calendar-check",
    "description": "大学生国家级考试倒计时与全流程查看（四六级/考研/教师资格/计算机等级/专四专八）。支持按单一考试筛选报名、准考证打印、口试/笔试等流程；CET 报名会提示各学校/考点时间可能不同，并可直达全国网上报名系统。数据在构建时由官方公告采集后内嵌。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 12,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "plugin-guide",
    "name": "插件使用说明",
    "version": "1.0.0",
    "author": "Le时间管理内置",
    "icon": "circle-question",
    "faIcon": "circle-question",
    "description": "按学习、效率、信息、生活与工具分类，用卡片快速查看每个内置插件的用途、使用步骤、平台支持和注意事项。",
    "permissions": [
      "ui"
    ],
    "entry": "main.js",
    "order": 99,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  }
];
const byId = {};
plugins.forEach((plugin) => { byId[plugin.id] = plugin; });
module.exports = { plugins, byId };
