#!/usr/bin/env node
/*
 * 三平台内置插件同步器。
 *
 * 单一事实源：01-windows/app/public/plugins/<id>/manifest.json + 对应内置数据。
 * - Windows：生成 src/pluginCatalog.js，插件宿主不再维护手写 ID 列表。
 * - Android：复用 01-windows/app 前端与 src-tauri，因此与 Windows 自动同源；这里做显式校验。
 * - 微信小程序：生成 core/pluginCatalog.js，并同步节假日/考试日历的离线数据，供原生适配页使用。
 *
 * 用法：在三端源码包根目录执行 `node tools/sync-plugins.js`。
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const DESKTOP_PLUGINS = path.join(ROOT, "01-windows", "app", "public", "plugins");
const DESKTOP_CATALOG = path.join(ROOT, "01-windows", "app", "src", "pluginCatalog.js");
const MINI_CORE = path.join(ROOT, "03-miniprogram", "core");
const MINI_CATALOG = path.join(MINI_CORE, "pluginCatalog.js");
const MINI_DATA = path.join(MINI_CORE, "pluginData");
const REQUIRED_PLATFORMS = ["windows", "android", "miniprogram"];
const VALID_STATUS = new Set(["full", "native", "conditional", "unavailable"]);

function fail(msg) {
  throw new Error(msg);
}
function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}
function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content.replace(/\r\n/g, "\n"), "utf8");
}
function compactManifest(man) {
  return {
    id: man.id,
    name: man.name,
    version: man.version,
    author: man.author || "",
    icon: man.icon || "puzzle-piece",
    faIcon: man.faIcon || "",
    description: man.description || "",
    permissions: Array.isArray(man.permissions) ? man.permissions : [],
    entry: man.entry || "main.js",
    order: Number(man.order) || 999,
    platforms: man.platforms,
  };
}

function loadManifests() {
  if (!fs.existsSync(DESKTOP_PLUGINS)) fail("找不到桌面端插件目录：" + DESKTOP_PLUGINS);
  const out = [];
  for (const dir of fs.readdirSync(DESKTOP_PLUGINS)) {
    const file = path.join(DESKTOP_PLUGINS, dir, "manifest.json");
    if (!fs.existsSync(file)) continue;
    const man = readJson(file);
    if (!man.id || man.id !== dir) fail(`manifest id 与目录不一致：${dir}`);
    if (!Number.isFinite(Number(man.order))) fail(`${dir}: 缺少 order`);
    if (!man.platforms || typeof man.platforms !== "object") fail(`${dir}: 缺少 platforms`);
    for (const platform of REQUIRED_PLATFORMS) {
      const status = man.platforms[platform];
      if (!VALID_STATUS.has(status)) fail(`${dir}: platforms.${platform}=${status} 非法`);
    }
    if (!fs.existsSync(path.join(DESKTOP_PLUGINS, dir, man.entry || "main.js"))) {
      fail(`${dir}: 找不到入口 ${man.entry || "main.js"}`);
    }
    out.push(compactManifest(man));
  }
  out.sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
  const ids = new Set();
  for (const man of out) {
    if (ids.has(man.id)) fail(`重复插件 ID：${man.id}`);
    ids.add(man.id);
  }
  return out;
}

function extractJsonObject(source, marker) {
  const startMarker = source.indexOf(marker);
  if (startMarker < 0) fail(`找不到数据标记：${marker}`);
  const start = source.indexOf("{", startMarker + marker.length);
  if (start < 0) fail(`找不到 ${marker} 后的对象`);
  let depth = 0, quote = null, escaped = false;
  for (let i = start; i < source.length; i++) {
    const ch = source[i];
    if (quote) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === quote) quote = null;
      continue;
    }
    if (ch === '"' || ch === "'") { quote = ch; continue; }
    if (ch === "{") depth++;
    if (ch === "}") {
      depth--;
      if (depth === 0) return source.slice(start, i + 1);
    }
  }
  fail(`无法解析 ${marker} 对象边界`);
}

function syncHolidayData() {
  const srcDir = path.join(DESKTOP_PLUGINS, "cn-holiday", "data");
  const years = {};
  for (const name of fs.readdirSync(srcDir).filter((x) => /^\d{4}\.json$/.test(x)).sort()) {
    const doc = readJson(path.join(srcDir, name));
    years[String(doc.year || name.slice(0, 4))] = doc;
  }
  write(
    path.join(MINI_DATA, "holiday.js"),
    "// Generated by tools/sync-plugins.js; do not edit by hand.\n" +
      "module.exports = " + JSON.stringify(years, null, 2) + ";\n"
  );
}

function syncExamData() {
  const file = path.join(DESKTOP_PLUGINS, "exam-calendar", "main.js");
  const source = fs.readFileSync(file, "utf8");
  const raw = extractJsonObject(source, "const DATA =");
  const data = JSON.parse(raw);
  write(
    path.join(MINI_DATA, "exams.js"),
    "// Generated by tools/sync-plugins.js from exam-calendar/main.js; do not edit by hand.\n" +
      "module.exports = " + JSON.stringify(data, null, 2) + ";\n"
  );
}

function main() {
  const manifests = loadManifests();
  if (!manifests.length) fail("没有发现内置插件");

  const desktop =
    "// Generated by tools/sync-plugins.js; edit plugin manifests then rerun the sync script.\n" +
    "export const BUILTIN_PLUGINS = " + JSON.stringify(manifests, null, 2) + ";\n" +
    "export const BUILTIN_IDS = BUILTIN_PLUGINS.map((plugin) => plugin.id);\n";
  write(DESKTOP_CATALOG, desktop);

  const mini =
    "// Generated by tools/sync-plugins.js; edit desktop plugin manifests then rerun the sync script.\n" +
    "const plugins = " + JSON.stringify(manifests, null, 2) + ";\n" +
    "const byId = {};\n" +
    "plugins.forEach((plugin) => { byId[plugin.id] = plugin; });\n" +
    "module.exports = { plugins, byId };\n";
  write(MINI_CATALOG, mini);

  syncHolidayData();
  syncExamData();

  // Android 与 Windows 共用 01-windows/app；只要 src-tauri 仍启用 mobile entry，就不存在第二份插件清单可漂移。
  const lib = path.join(ROOT, "01-windows", "app", "src-tauri", "src", "lib.rs");
  if (!fs.existsSync(lib) || !fs.readFileSync(lib, "utf8").includes("cfg_attr(mobile, tauri::mobile_entry_point)")) {
    fail("Android 共用 Tauri 后端关系未通过校验");
  }

  const miniNative = manifests.filter((x) => x.platforms.miniprogram === "native").map((x) => x.id);
  console.log(`✓ 已同步 ${manifests.length} 个内置插件`);
  console.log(`  Windows / Android：${manifests.length} 个同源`);
  console.log(`  微信小程序原生适配：${miniNative.length} 个 (${miniNative.join(", ")})`);
}

main();
